# Имя нашего workflow, которое будет отображаться на GitHub
name: CI Pipeline

# Триггер: Указываем, когда запускать этот workflow.
# В нашем случае - при каждом 'push' в ветку 'main'.
on:
  push:
    branches: [ "main" ]

# Задания: Список работ, которые нужно выполнить.
# У нас будет одна работа под названием 'build'.
jobs:
  build:
    # Указываем, на какой операционной системе будет работать наш CI.
    # 'ubuntu-latest' — это стандарт для CI/CD.
    runs-on: ubuntu-latest

    # Шаги: Последовательность действий, которые нужно выполнить в рамках работы 'build'.
    steps:
      # Шаг 1: Клонируем наш репозиторий на виртуальную машину GitHub.
      # 'uses' означает, что мы используем готовое действие (action) от сообщества.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Собираем Docker-образ.
      # Мы даем ему такое же имя, как и локально.
      - name: Build Docker image
        run: docker build -t my-devops-app .

      # Дополнительный шаг (для проверки): Показываем список созданных образов.
      - name: List Docker images
        run: docker images