name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ШАГ 1: Вход в Docker Hub
      # Мы используем готовый action для логина
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ШАГ 2: Сборка и отправка Docker-образа
      # Этот action умеет и собирать (build), и отправлять (push) образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Тег (имя) образа будет выглядеть как "ваш_логин/имя_репозитория:latest"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-project:latest